@startuml
header Análise Orientada a Objetos - 3º Semestre - Unopar - Análise e Desenvolvimento de Sistemas

title Sistema de Locação de Veículos

footer Giulia Marcela Mendes de Arruda

!theme carbon-gray

class Empresa {
  - nome: String
  - cnpj: String {unique}
}

class Automovel {
  placa: String {unique}
  cor: String
  ano: Integer
  tipoCombustivel: String
  numeroPortas: Integer
  quilometragem: Long
  renavam: String
  chassi: String
  valor: Double
  disponibilidade: Boolean
}

class Cliente {
  - nome: String
  - cpf: String {unique}
  - rg: String
  - cnh: String
  - email: String
  - telefoneResidencial: String
  - telefoneCelular: String
}

class Endereco {
  - cep: String {unique}
  - logradouro: String
  - complemento: String
  - bairro: String
  - localidade: String
  - uf: String
  - ddd: int
}

class Marca {
  - nome: String
}

class Modelo {
  - nome: String
}

class Locacao {
  - codigo: UUID {unique}
  - dataHoraInicio: LocalDateTime
  - dataHoraDevolucao: LocalDateTime
}

Empresa "1" *-- "*" Automovel : possui
Cliente "1" *-- "1" Endereco : reside
Modelo "1" -- "*" Automovel : possui
Marca "1" - "*" Modelo : refere-se
Automovel "1" o- "*" Locacao : locado por 
Locacao "*" -o "1" Cliente : loca

@enduml